Random Plots for visualisation during the coding process

```{r, libraries}
# used packages
library(ggplot2)
library(ggpubr)
library(rnaturalearth)
library(sf)
library(sp)
library(terra)
library(ncdf4)
library(dplyr)
```

```{r, bboxes}
## plot cleaned occurence data with native extent and extent of interest
sf_use_s2(FALSE) # to get rectangular intersect boxes instead of a projection

occs_global <- readRDS("F:/BscBio_LP23_data/occurence/axyridis_clean.rds")
occs_global_sf <- st_as_sf(occs_global, coords = c(
    "decimalLongitude",
    "decimalLatitude"
), crs = 4326)
countries <- ne_countries(scale = "medium", returnclass = "sf")
countries <- st_transform(countries, crs = 4326)

# create boundary boxes for europe and asia (native range)
# extent of europe
eu_box <- c(xmin = -25, ymin = 35, xmax = 65, ymax = 72)
class(eu_box) <- "bbox"
eu_box <- st_as_sfc(eu_box)
eu_box <- st_as_sf(eu_box, crs = 4326)
in_eu <- st_intersects(eu_box, occs_global_sf, sparse = FALSE)
occs_eu <- occs_global[as.vector(in_eu), ]

# extent of native range (Orlova-Bienkowskaja, Ukrainsky & Brown, 2015)
as_box <- c(xmin = 70, ymin = 20, xmax = 150, ymax = 65)
class(as_box) <- "bbox"
as_box <- st_as_sfc(as_box)
as_box <- st_as_sf(as_box, crs = 4326)
in_as <- st_intersects(as_box, occs_global_sf, sparse = FALSE)
occs_as <- occs_global[as.vector(in_as), ]
```

```{r}
# plot points in extents
map <- ggplot(countries) +
    geom_sf(data = countries, colour = "black", fill = "white") +
    xlim(-25, 65) +
    ylim(35, 72) +
    geom_point(
        data = occs_global, aes(x = decimalLongitude, y = decimalLatitude),
        colour = "cyan", alpha = 0.8
    ) +
    geom_point(
        data = occs_eu, aes(x = decimalLongitude, y = decimalLatitude),
        colour = "blue", alpha = 0.8
    )
map
```

```{r}
# plot points in extents
map <- ggplot(countries) +
    geom_sf(data = countries, colour = "black", fill = "white") +
    xlim(70, 150) +
    ylim(20, 65) +
    geom_point(
        data = occs_global, aes(x = decimalLongitude, y = decimalLatitude),
        colour = "cyan", alpha = 0.8
    ) +
    geom_point(
        data = occs_as, aes(x = decimalLongitude, y = decimalLatitude),
        colour = "blue", alpha = 0.8
    )
plot(map)
```

```{r}
max(occs_global$coordinateUncertaintyInMeters)
hist(occs_global$coordinateUncertaintyInMeters)
hist(occs_global$year)
```

```{r, plot lc val test}
lc_16 <- rast("data/cropped_rasters/Cop_LC_2016_eu.grd")
lc_16_v <- lc_16 == 200
plot(lc_16_v)
```

```{r, plot glob raw vs clean gbif}
# load raw gbif raster
axyridis_raw <- read.csv("R/data/occurence_data/Harmonia-axyridis_gbif_raw.csv",
    header = TRUE,
    sep = "\t"
)
axyridis_clean <- readRDS("R/data/occurence_data/axyridis_clean.rds")

## plot global on countries map
countries <- ne_countries(scale = "medium", returnclass = "sf")
countries <- st_transform(countries, crs = 4326)
m_glob <- ggplot(countries) +
    geom_sf(data = countries, colour = "black", fill = "white") +
    geom_point(
        data = axyridis_raw, aes(x = decimalLongitude, y = decimalLatitude),
        colour = "darkgreen", alpha = 0.7
    ) +
    geom_point(
        data = axyridis_clean, aes(x = Lon, y = Lat),
        colour = "blue", alpha = 0.7
    )
ggsave(m_glob, filename = "R/plots/gbif_raw_vs_clean_global.png")
```

```{r, plot lc with map}
countries <- ne_countries(scale = "medium", type = "countries", returnclass = "sf")
countries <- st_transform(countries, crs = crs(lc_16_eu))
m_lc <- ggplot(countries) +
    geom_raster(lc_16_eu, aes(fill = lccs_class, alpha = 0.5))
ggsave(m_lc, filename = "R/data/plotting/lc_glob_extents.pdf")
```

```{r, how many raw occs before 2002 eu and as}
# create uncleaned eu and as subsets (modified copy of occ_clean)
# load raw gbif data
axyridis_raw <- read.csv("R/data/occurence_data/Harmonia-axyridis_gbif_raw.csv",
    header = TRUE,
    sep = "\t"
)

# only take relevant columns
axyridis_raw <- axyridis_raw[c("decimalLatitude", "decimalLongitude", "year", "coordinateUncertaintyInMeters")]
names(axyridis_raw) <- c("Lat", "Lon", "Year", "CoordUncert")

# remove relevant NAs in data
# remove occurences after 2022
axyridis_sub <- subset(axyridis_raw, !is.na(Lat & Lon & Year & CoordUncert))

# subset data into eu and as spatial extent
# land cover layers vor reference (xmin, xmax, ymin, ymax)
eu <- ext(rast("R/data/cropped_rasters/Cop_LC_2016_eu.grd"))
as <- ext(rast("R/data/cropped_rasters/Cop_LC_2016_as.grd"))
# some issue with crop and SpatVector with terra, so ugly subset
axyridis_eu <- subset(axyridis_sub, Lon > eu[1] & Lon < eu[2] & Lat > eu[3] & Lat < eu[4])
axyridis_as <- subset(axyridis_sub, Lon > as[1] & Lon < as[2] & Lat > as[3] & Lat < as[4])

eu_bef2k <- count(subset(axyridis_eu, Year < 2002))[[1]]
as_bef2k <- count(subset(axyridis_as, Year < 2002))[[1]]
print(paste("Raw EU < 2002:", eu_bef2k, "Raw Native < 2002:", as_bef2k))
```

```{r, plot yearly occ frequency 2002-2022 with cleaned occs}
occs <- readRDS("R/data/occurence_data/axyridis_clean.rds")
occs_eu <- subset(occs, Area == "EU" & Year >= 2002)
occs_as <- subset(occs, Area == "AS" & Year >= 2002)

# get occurences per year as df
freq_eu <- count(occs_eu, Year) # frequency of yearly occs eu
freq_as <- count(occs_as, Year) # frequency of yearly occs as
freqs <- data.frame(Year = 2002:2022, n = 0)
freqs[match(freq_eu$Year, freqs$Year), ] <- freq_eu # add missing years
freqs_tot <- data.frame(Year = freqs$Year, n_eu = freqs$n)
freqs <- data.frame(Year = 2002:2022, n = 0)
freqs[match(freq_as$Year, freqs$Year), ] <- freq_as # add missing years
freqs_tot$n_as <- freqs$n
freqs_tot$n_tot <- freqs_tot$n_eu + freqs_tot$n_as
# reformat df to long format for ggplot
l <- length(freqs$Year)
frequencies <- data.frame(
    Year = c(freqs_tot$Year, freqs_tot$Year, freqs_tot$Year),
    n = c(freqs_tot$n_as, freqs_tot$n_eu, freqs_tot$n_tot),
    label = c(rep("Native", l), rep("EU", l), rep("Total", l))
)

# find out how many occurences are before 2000
eu_bef2k <- count(subset(occs, Area == "EU" & Year < 2002))[[1]]
as_bef2k <- count(subset(occs, Area == "AS" & Year < 2002))[[1]]
cap <- paste("Cleaned EU < 2002:", eu_bef2k, "Cleaned Native < 2002:", as_bef2k)
plot <- ggplot(frequencies, aes(x = Year, y = n)) +
    geom_point(alpha = 0.5, aes(colour = label)) +
    labs(title = "cleaned yearly occurrences", caption = cap)
plot
ggsave(plot, filename = "R/plots/clean_occ_yearly_tot_eu_as.png")
logplot <- plot + scale_y_continuous(trans = "log10")
logplot
ggsave(logplot, filename = "R/plots/clean_occ_yearly_tot_eu_as_log.png")
print(cap)
```

```{r, test absence distance flagging}
test <- buffer(vect(rbind(c(0, 0), c(1, 1)), crs = "+proj=longlat"), 10000)[1]
set.seed(54)
t_pres <- spatSample(test, 5)
gen <- spatSample(test, 100)
flag <- gen[apply(distance(gen, t_pres), 1, function(x) any(x < 1500)), ]
plot(test)
points(t_pres, col = "green")
points(gen, col = "grey")
points(flag, col = "red")
```

```{r, test distance with 2 buffer circles}
s <- Sys.time()
set.seed(54)
n <- 20 # number of test presence points
n_ab <- 20 # number of generated points
t_area <- vect(ext(c(0, 1, 0, 1)), crs = "+proj=longlat")
t_pts <- spatSample(t_area, n)
t_pts$Year <- sample(c(2010:2015), n, replace = TRUE)
t_pts$Area <- sample(c("EU", "AS"), n, replace = TRUE)

r_circs <- buffer(t_pts, 10000)
d_circs <- buffer(t_pts, 2000)
d_circs <- d_circs[, -(1:ncol(d_circs))] # remove value cols from d_circs
# so that erase only iterates once
# d_comb <- combineGeoms(d_circs[1:2], d_circs[-2])
# d_comb <- combineGeoms(d_comb[1], d_comb[2])
t_rd <- erase(r_circs, d_circs)
all_gen <- t_pts[1]
for (i in seq_along(t_rd)) {
    c <- t_rd[i]
    gen <- spatSample(c, n_ab)
    all_gen <- rbind(all_gen, gen)
}
all_gen <- all_gen[-1, ]
nrow(all_gen)
print(Sys.time() - s)

plot(all_gen, "Year", col = rainbow(5), alpha = 0.6) # , xlim=c(0,0.1), ylim=c(0,0.1))
points(t_pts)
lines(t_rd)
```

```{r, test improve erase}
set.seed(54)
n <- c(100, 1000, 10000) # number of test presence points
n_ab <- 5 # number of generated points
t_area <- vect(ext(c(0, 20, 0, 20)), crs = "+proj=longlat")
t_pts <- spatSample(t_area, n)
t_pts$Year <- sample(c(2010:2015), n, replace = TRUE)
t_pts$Area <- sample(c("EU", "AS"), n, replace = TRUE)

btime <- Sys.time()
r_circs <- buffer(t_pts, 10000)
d_circs <- buffer(t_pts, 2000)
d_circs <- d_circs[, -(1:ncol(d_circs))] # remove value cols from d_circs
# so that erase only iterates once
d_comb <- combineGeoms(d_circs[1:2], d_circs[-2])
d_comb <- combineGeoms(d_comb[1], d_comb[2])
t_rd <- erase(r_circs, d_circs)
gentime <- Sys.time()
all_gen <- t_pts[1]
for (i in seq_along(t_rd)) {
    c <- t_rd[i]
    gen <- spatSample(c, n_ab)
    all_gen <- rbind(all_gen, gen)
}
all_gen <- all_gen[-1, ]
fintime <- Sys.time()


plot(all_gen, "Year", col = rainbow(5), alpha = 0.6) # , xlim=c(0,0.1), ylim=c(0,0.1))
points(t_pts)
lines(t_rd)
```

```{r, test erase 10k no split}
t_area <- vect(ext(c(0, 20, 0, 20)), crs = "+proj=longlat")
n_ab <- 5 # number of generated points
n <- 10000
pres <- readRDS("R/data/occurence_data/axyridis_clean.rds")
pres <- subset(pres, Year == 2019)

btime <- Sys.time()
t_pts <- vect(pres, geom = c("Lon", "Lat"), crs = "epsg:4326")
r_circs <- buffer(t_pts, 10000)
d_circs <- buffer(t_pts, 1000)
d_circs <- d_circs[, -(1:ncol(d_circs))] # remove value cols from d_circs
t_rd <- erase(r_circs, d_circs)

cat("no splits: ", n, " pts: ")
print(Sys.time() - btime)
```

```{r, benchmark absence gen (runtime 38 mins) }
rtime <- Sys.time()
set.seed(4326)
source("R/0.0-functions.r", encoding = "UTF-8")
# use lc_eu as ref
lc_eu <- rast("R/data/cropped_rasters/Cop_LC_2002_eu.grd")
# presence points per test
counts <- c(1000, 5000, 10000)
# extents for each element of pts
exts <- rbind(
    c(2, 3, 41, 42),
    c(0, 5, 40, 45),
    c(-5, 5, 35, 45)
)

results <- c(0, 0, 0)
all_subexts <- c(0, 0, 0, 0)

for (i in seq_len(nrow(exts))) {
    print(i)
    pcnt <- counts[i]
    t_ext <- exts[i, ]
    # create dummy lc_ref
    mat <- matrix(c(rep(50, 10), NA, rep(50, 5)), nrow = 4, ncol = 4)
    t_ref <- rast(mat, crs = "epsg:4326")
    ext(t_ref) <- ext(t_ext)
    names(t_ref) <- "lccs_class"
    t_ref <- disagg(t_ref, fact = pcnt / 100)
    # generate dummy presences
    bias <- 0.6 # percent of presences that should be biased
    init_pts <- spatSample(t_ref, pcnt * (1 - bias), xy = TRUE, na.rm = TRUE)
    init_v <- vect(init_pts, geom = c("x", "y"), crs = crs(t_ref))
    biased_v <- init_v[1:(pcnt * bias / 10), ]
    biased_c <- buffer(biased_v, pcnt)
    t_pres <- rbind(init_v, spatSample(biased_c, pcnt * bias))
    # cat(length(init_v), length(biased_v) * 10, "\n")
    #plot(t_ref)
    #points(t_pres, pch = 16)

    # benchmark without subsets
    tot_time <- Sys.time()
    e_cnt <- pcnt
    pa <- data.frame() # initialize pa df
    ext_e <- vect(ext(t_ext), crs = crs(t_ref))
    # subset occurences inside the extent in question
    pres_c <- crop(t_pres, ext(ext_e))
    # generate absences inside the extent
    pa_e <- lp_gen_abs(pres_c, n_abs = 5, min_d = 1000, max_d = 10000, t_ref)
    # merge with already computed points
    pa <- rbind(pa, pa_e)

    td <- difftime(Sys.time(), tot_time, units = "secs")[[1]]
    cat("\n", "TIME:", td, "s", "|pcnt", pcnt, "|e_cnt", e_cnt, "\n")
    results <- rbind(results, c(td, pcnt, e_cnt))

    # start benchmarking subextents
    t_endcounts <- ceiling(c(pcnt / 10, pcnt / 2, pcnt / 100))
    for (j in seq_along(t_endcounts)) {
        tot_time <- Sys.time()
        e_cnt <- t_endcounts[j]
        subexts <- lp_subdiv_pts(t_pres, e_cnt, t_ext)
        pa <- data.frame() # initialize pa df
        prog <- 0
        for (e in seq_len(nrow(subexts))) {
            cat("\r", "|", prog, "|")
            prog <- prog + 1
            ext_e <- vect(ext(subexts[e, ]), crs = crs(t_ref))
            # subset occurences inside the extent in question
            pres_c <- crop(t_pres, ext(ext_e))
            # generate absences inside the extent
            pa_e <- lp_gen_abs(pres_c, n_abs = 5, min_d = 1000, max_d = 10000, lc_ref)
            # merge with already computed points
            pa <- rbind(pa, pa_e)
        }
        td <- difftime(Sys.time(), tot_time, units = "secs")[[1]]
        cat("\n", "TIME:", td, "s", "|pcnt", pcnt, "|e_cnt", e_cnt, "\n")
        results <- rbind(results, c(td, pcnt, e_cnt))
    }
}
saveRDS(results, file = "R/data/plotting/gen_benchmarkresults_dummy.rds")
print(Sys.time() - rtime) # total runtime of cell
```

```{r, barplot with dummy benchmark results}
results <- readRDS("R/data/plotting/gen_benchmarkresults_dummy.rds")
res <- as.data.frame(results[-1, ])
names(res) <- c("runtime", "pcnt", "e_cnt")
res$runtime <- res$runtime / 60 # runtime in mins
mat <- matrix(nrow = 3, ncol = 4)
rownames(mat) <- unique(res$pcnt)
colnames(mat) <- c("1", "1/10", "1/2", "1/100")
mat[1, ] <- res$runtime[1:4]
mat[2, ] <- res$runtime[5:8]
mat[3, ] <- res$runtime[9:12]
mat[, 2:3] <- mat[, 3:2]
colnames(mat) <- c("1", "1/2", "1/10", "1/100")

png(width = 600, height = 600, file = "R/data/plotting/abs_gen_subdiv_bench_dummy.png")
barplot(mat,
    col = rainbow(3), beside = TRUE,
    main = "Runtime comparison of different subset resolutions (min) with dummy data",
    ylab = 'runtime (mins)', xlab = 'relative subdivision limit'
)
legend("topleft", legend = rownames(mat), fill = rainbow(3))
dev.off()
# mat <- t(mat)  transpose for different orientation
# barplot(mat, col = rainbow(4), beside = TRUE)
# legend("topleft", legend = rownames(mat), fill = rainbow(3))
```

```{r, benchmark abs_gen with cleaned data (runtime 57 mins)}
rtime <- Sys.time()
set.seed(4326)
source("R/0.0-functions.r", encoding = "UTF-8")
# load cleaned occurences
occs <- readRDS("R/data/occurence_data/axyridis_clean.rds")
# load reference lc layers
lc_eu <- rast("R/data/cropped_rasters/Cop_LC_2002_eu.grd")
lc_as <- rast("R/data/cropped_rasters/Cop_LC_2002_as.grd")
t_ref <- merge(lc_eu, lc_as)
# ext(lc_ref) returns:
# SpatExtent : -25, 150, 19.9916666666667, 72 (xmin, xmax, ymin, ymax)
# lc_ref extent as vector for subdiv function
t_ext <- c(-25, 150, 19.9916666666667, 72)

results <- c(0, 0, 0) # initialize results

for (i in 1:3) {
    if (i == 1) {
        t_occs <- rbind(subset(occs, Year == 2005), subset(occs, Year == 2002))
    } else {
        if (i == 2) {
            t_occs <- subset(occs, Year == 2014)
        } else {
            t_occs <- subset(occs, Year == 2019)
        }
    }
    print(i)
    t_pres <- vect(t_occs, geom = c("Lon", "Lat"), crs = crs(t_ref))
    pcnt <- nrow(t_pres)
    # benchmark without subsets
    tot_time <- Sys.time()
    e_cnt <- pcnt
    pa <- data.frame() # initialize pa df
    ext_e <- vect(ext(t_ext), crs = crs(t_ref))
    # generate absences inside the extent
    pa_e <- lp_gen_abs(t_pres, n_abs = 5, min_d = 1000, max_d = 18000, t_ref)
    # merge with already computed points
    pa <- rbind(pa, pa_e)

    td <- difftime(Sys.time(), tot_time, units = "secs")[[1]]
    cat("\n", "TIME:", td, "s", "|pcnt", pcnt, "|e_cnt", e_cnt, "\n")
    results <- rbind(results, c(td, pcnt, e_cnt))

    # start benchmarking subextents
    t_endcounts <- ceiling(c(pcnt / 5, pcnt / 2, pcnt / 10))
    for (j in seq_along(t_endcounts)) {
        tot_time <- Sys.time()
        e_cnt <- t_endcounts[j]
        subexts <- lp_subdiv_pts(t_pres, e_cnt, t_ext)
        pa <- data.frame() # initialize pa df
        prog <- 0
        for (e in seq_len(nrow(subexts))) {
            cat("\r", "|", prog, "|")
            prog <- prog + 1
            ext_e <- vect(ext(subexts[e, ]), crs = crs(t_ref))
            # subset occurences inside the extent in question
            pres_c <- crop(t_pres, ext(ext_e))
            # crop lc_ref to extent i question
            t_ref_c = crop(t_ref, ext(ext_e))
            # generate absences inside the extent
            pa_e <- lp_gen_abs(pres_c, n_abs = 5, min_d = 1000, max_d = 18000, t_ref_c)
            # merge with already computed points
            pa <- rbind(pa, pa_e)
        }
        td <- difftime(Sys.time(), tot_time, units = "secs")[[1]]
        cat("\n", "TIME:", td, "s", "|pcnt", pcnt, "|e_cnt", e_cnt, "\n")
        results <- rbind(results, c(td, pcnt, e_cnt))
    }
}
saveRDS(results, file = "R/data/plotting/gen_benchmarkresults_axyridis.rds")
print(Sys.time() - rtime) # total runtime of cell
```

```{r, barplot with occurence benchmark results}
results <- readRDS("R/data/plotting/gen_benchmarkresults_axyridis.rds")
res <- as.data.frame(results[-1, ])
names(res) <- c("runtime", "pcnt", "e_cnt")
res$runtime <- res$runtime / 60 # runtime in mins
mat <- matrix(nrow = 3, ncol = 4)
rownames(mat) <- unique(res$pcnt)
mat[1, ] <- res$runtime[1:4]
mat[2, ] <- res$runtime[5:8]
mat[3, ] <- res$runtime[9:12]
mat[, 2:3] <- mat[, 3:2]
colnames(mat) <- c("1", "1/2", "1/5", "1/10")

png(width = 600, height = 600, file = "R/plots/abs_gen_subdiv_bench_axyridis.png")
barplot(mat,
    col = rainbow(3), beside = TRUE,
    main = "Runtime comparison of different subset resolutions with occurrence subsets",
    ylab = 'runtime (mins)', xlab = 'relative subdivision limit'
)
legend("topleft", legend = rownames(mat), fill = rainbow(3))
dev.off()
```

```{r, test plot pa from gen}
pa <- readRDS("R/data/occurence_data/axyridis_pa.rds")
pa_as <- subset(pa, Area == "AS")
pa_as_v <- vect(pa_as, geom = c("Lon", "Lat"), crs = "epsg:4326")
v_crop <- crop(pa_as_v, ext(87.85, 88.35, 53.4, 53.85))

crop_df <- as.data.frame(v_crop, geom = "XY")
pres_v <- vect(subset(crop_df, Presence == "present"), geom = c("x", "y"), crs = "epsg:4326")

r_crop <- buffer(pres_v, 10000)
d_crop <- buffer(pres_v, 1000)

plot(v_crop,
    "Presence",
    col = c("grey", "green"),
    xlim = c(87.85, 88.35),
    ylim = c(53.55, 53.85)
)
lines(r_crop)
lines(d_crop)
```

```{r,plot axyridis subdiv extents}
subexts <- readRDS("R/data/plotting/axyridis_abs_gen_subexts.rds")
ref_ext <- c(-25, 150, 19.9916666666667, 72)

# countries map
countries <- ne_countries(scale = "medium", returnclass = "sf")
countries <- st_transform(countries, crs = 4326)
countries <- vect(countries)

# rough aspect ratio of lon and lat
r <- 175 / 92
png(width = 600 * r, height = 600, file = "R/plots/glob_subdiv_exts_axyridis.png")
plot(crop(countries, ext(ref_ext)), 
    main = "used subextents for absence generation"
)
for (s in seq_len(nrow(subexts))) {
    ext_s <- ext(subexts[s, ])
    lines(vect(ext_s, crs = "epsg:4326"), col = "blue")
}
dev.off()
```

```{r, plot subext border error example}
subexts = tail(readRDS("R/data/plotting/axyridis_abs_gen_subexts.rds"), 4)
pa = readRDS("R/data/occurence_data/axyridis_pa.rds")
ref_ext = ext(c(4.2, 4.6, 51.2, 51.4))
pa_crop = crop(vect(pa, geom = c("Lon", "Lat"), crs = "epsg:4326"), ref_ext)

# generate min dist circles 
po = subset(pa, Presence == 'present')
po_crop = crop(vect(po, geom = c("Lon", "Lat"), crs = "epsg:4326"), ref_ext)
r_crop = buffer(po_crop, 10000)
d_crop <- buffer(po_crop, 1000)
rd_crop = erase(r_crop, d_crop)
d_rast <- rasterize(rd_crop, rast(rd_crop, ncols=500, nrows=500), "Presence")
# flag wrong absences
ao = subset(pa, Presence == 'absent')
ao_crop = crop(vect(ao, geom = c("Lon", "Lat"), crs = "epsg:4326"), ref_ext)
ao_flag = cbind(ao_crop, extract(d_rast, ao_crop, ID = FALSE))
ao_flag[, 4] = NULL # remove Presence duplicate
ao_flag = ao_flag[is.na(ao_flag$Presence), ]
#plot(po_crop, "Presence", col = c("grey", "green"))
plot(d_rast)
for (s in seq_len(nrow(subexts))) {
    ext_s <- ext(subexts[s, ])
    lines(vect(ext_s, crs = "epsg:4326"), col = "blue")
}
points(ao_flag, col = "red")
print(length(ao_flag) / length(ao_crop))
```
